name: global_dhikr_final
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.12.11
  provider: ^3.2.0
  get_it: ^3.0.3
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.3
  intl: ^0.15.7
  firebase_auth: ^0.14.0+5
  mvc_pattern: ^3.4.3
  splashscreen: ^1.2.0
  intro_views_flutter: ^2.8.0
  font_awesome_flutter: ^8.5.0
  google_sign_in: ^4.1.1
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0-rc
  shared_preferences: ^0.5.6
  date_format: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/masjidBackground.jpg
    - images/earth.jpg
    - images/lamp.jpg
    - images/tree.jpg